ORG 00H
MOV P0, #0FFH		;DEFINE P0 AS INPUT PORT
MOV P2, #00H		;DEFINE P2 AS OUTPUT PORT



HERE: 	JB P0.0, FORWARD	;IF P0.0 IS 1 MOVE FORWARD
	JB P0.1, LEFTWARD	;IF P0.1 IS 1 MOVE LEFTWARD
	JB P0.2, RIGHTWARD	;IF P0.2 IS 1 MOVE RIGHTWARD
	JB P0.3, BACKWARD	;IF P0.3 IS 1 MOVE BACKWARD
	SJMP HERE
	
FORWARD:			;MOVE FORWARD
	SETB P2.6
	SETB P2.1
	CLR P2.0
	CLR P2.7
	RET
		
BACKWARD:			;MOVE BACKWARDS
	CLR P2.6
	CLR P2.1
	SETB P2.0
	SETB P2.7
	RET
	
LEFTWARD:			;MOVE LEFT
	SETB P2.6
	CLR P2.1
	CLR P2.0
	CLR P2.7
	RET

RIGHTWARD:			;MOVE RIGHT
	CLR P2.6
	SETB P2.1
	CLR P2.0
	CLR P2.7
	RET
END


